auth_controllers:
    resource:
        path: ../src/Auth/Infrastructure/Http/Controller/
        namespace: App\Auth\Infrastructure\Http\Controller
    type: attribute

review_controllers:
    resource:
        path: ../src/Review/Infrastructure/Http/Controller/
        namespace: App\Review\Infrastructure\Http\Controller
    type: attribute
api_auth_login:
    path: /api/auth/login
