# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    elasticsearch_host: '%env(ELASTICSEARCH_URL)%'
    elasticsearch_index_prefix: '%env(ELASTICSEARCH_INDEX_PREFIX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Domain/Entity/'
            - '../src/*/Domain/ValueObject/'
            - '../src/*/Domain/Event/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher: ~

    Elastic\Elasticsearch\Client:
        factory: [ 'Elastic\Elasticsearch\ClientBuilder', 'fromConfig' ]
        arguments:
            - hosts: [ '%elasticsearch_host%' ]

    App\Review\Infrastructure\Search\ElasticsearchReviewIndexer:
        arguments:
            $indexPrefix: '%elasticsearch_index_prefix%'

    App\Review\Infrastructure\Search\SearchEngineReviewSearch:
        arguments:
            $indexPrefix: '%elasticsearch_index_prefix%'

    App\Review\Infrastructure\Console\CreateReviewIndexCommand:
        arguments:
            $indexPrefix: '%elasticsearch_index_prefix%'
